apiVersion: v1
kind: ServiceAccount
metadata:
  name: talos-lb-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: talos-lb-controller
rules:
  - apiGroups: [""]
    resources: ["services", "services/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: talos-lb-controller
subjects:
  - kind: ServiceAccount
    name: talos-lb-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: talos-lb-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: talos-lb-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: talos-lb-controller
  template:
    metadata:
      labels:
        app: talos-lb-controller
    spec:
      serviceAccountName: talos-lb-controller
      hostNetwork: true
      containers:
        - name: controller
          image: ghcr.io/tcurdt/talos-servicelb:latest
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          volumeMounts:
            - name: sbin
              mountPath: /sbin
              readOnly: true
            - name: lib
              mountPath: /lib
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: sbin
          hostPath:
            path: /sbin
            type: Directory
        - name: lib
          hostPath:
            path: /lib
            type: Directory
